export enum Tables {
  TrainingPlan = 'training_plans',
  User = 'users',
  UserFollows = 'user_follows',
  UserPrivacySettings = 'user_privacy_settings',
  PlanSubscription = 'plan_subscription',
  PlanDayProgress = 'plan_day_progress',
  Day = 'days',
  Exercise = 'exercises',
  ExerciseLog = 'exercise_logs',
  PlanInvite = 'plan_invites',
  TrainingPlanFeedback = 'training_plan_feedbacks',
  TrainingPlanParticipants = 'plan_participant',
  TrainingPlanLikes = 'training_plan_likes',
  WeightLog = 'weight_logs',
  BodyMeasurement = 'body_measurements',
}
