name: E2E Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres-16
        ports: ['5432:5432']
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - name: Chechout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{inputs.node-version}}

      - name: Install dependencies
        run: npm ci

      - name: Run migrations
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/testdb
        run: |
          npm run db:migrate

      - name: Start app in background
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/testdb
        run: |
          npm run build
          nohup npm run start &
          sleep 10

      - name: Run E2E tests
        env:
          DATABASE_URL: postgres://test:test@localhost:5432/testdb
        run: npm run test:e2e
